backend:
  name: git-gateway
  repo: sharibarboza/FilcanJS #replace with your username/repo
  branch: dev

media_folder: static/assets
public_folder: /assets

collections:
  - name: campmeeting_date
    label: Campmeeting Date
    folder: dates
    create: true
    fields:
      - { label: Unique title to file this date (e.g. Camp Meeting 2019), name: title, widget: string }
      - { label: Date, name: date, widget: date }

  - name: leadership
    label: Leadership
    folder: leadership
    create: true
    fields:
      - { label: Unique title to file this executive (e.g. VP-Edmonton), name: title, widget: string }
      - { label: Executive Position, name: position, widget: string }
      - { label: Name, name: name, widget: string }
      - { label: Photo, name: photo, widget: image, required: false, default: ../static/assets/default.jpg }
      - { label: Executive Type, name: type, widget: select, options: ['Officer', 'Board VP', 'Adviser', 'Chair', 'Youth'] }

  - name: church
    label: Church
    folder: churches
    create: true
    fields:
      - { label: Name of church, name: title }
      - { label: City/Town, name: city, widget: string }
      - { label: Current Pastor, name: pastor, widget: string, required: false }
      - { label: Address, name: address, widget: string }
      - { label: Phone, name: phone, widget: string, required: false }
      - { label: Website, name: website, widget: string, required: false }
      - { label: Photo, name: photo, widget: image, required: false, default: /assets/sda-logo-blue.png }

  - name: pages
    label: Pages
    files:
      - label: History Page
        name: history
        file: content/history.md
        fields:
          - { label: Title of Page, name: title, widget: string }
          - { label: Photo, name: photo, widget: image }
          - { label: Text Content, name: content, widget: markdown }
