backend:
  name: git-gateway
  repo: sharibarboza/FilcanJS #replace with your username/repo
  branch: dev

media_folder: static/assets
public_folder: /assets

collections:
  - name: campmeeting_date
    label: Campmeeting Date
    folder: cms/dates
    create: true
    fields:
      - { label: Unique title to file this date (e.g. Camp Meeting 2019), name: title, widget: string }
      - { label: Date, name: date, widget: date }

  - name: leadership
    label: Leadership
    folder: cms/leadership
    create: true
    fields:
      - { label: Unique title to file this executive (e.g. VP-Edmonton), name: title, widget: string }
      - { label: Executive Position, name: position, widget: string }
      - { label: Name, name: name, widget: string }
      - { label: Photo, name: photo, widget: image, required: false, default: assets/default.jpg }
      - { label: Executive Type, name: type, widget: select, options: ['Officer', 'Board VP', 'Adviser', 'Chair', 'Youth'] }

  - name: church
    label: Church
    folder: cms/churches
    create: true
    fields:
      - { label: Name of church, name: title }
      - { label: City/Town, name: city, widget: string }
      - { label: Current Pastor, name: pastor, widget: string, required: false }
      - { label: Address, name: address, widget: string }
      - { label: Phone, name: phone, widget: string, required: false }
      - { label: Website, name: website, widget: string, required: false }
      - { label: Photo, name: photo, widget: image, required: false, default: /assets/sda-logo-blue.png }

  - name: pages
    label: Pages
    files:
      - label: History Page
        name: history
        file: cms/pages/history/history.md
        fields:
          - { label: Title of Page, name: title, widget: string }
          - { label: Photo, name: photo, widget: image }
          - { label: Text Content, name: content, widget: markdown }

  - name: bylaws
    label: Bylaws
    folder: cms/files/bylaws
    create: true
    fields:
      - { label: Title of Bylaw File, name: title, widget: string }
      - { label: File, name: file, widget: file }

  - name: reports
    label: Annual Reports
    folder: cms/files/reports
    create: true
    fields:
      - { label: Title of Report, name: title, widget: string }
      - { label: File, name: file, widget: file }

  - name: grid
    label: Grid Images
    folder: cms/grid
    create: true
    fields:
      - { label: Photo Number (e.g. Photo 1), name: title, widget: string }
      - { label: Event, name: event, widget: string }
      - { label: Caption, name: caption, widget: string }
      - { label: Photo, name: photo, widget: image }

  - name: theme
    label: Camp Meeting Theme
    folder: cms/theme
    fields:
      - { label: Theme Slogan, name: title, widget: string }
      - { label: Bible Verse Text, name: versetext, widget: string }
      - { label: Bible Verse (e.g. Luke 14:23), name: verse, widget: string }

  - name: speakers
    label: Camp Meeting Speakers
    folder: cms/speakers
    create: true
    fields:
      - { label: Name of speaker, name: title, widget: string }
      - { label: Type of speaker (e.g. Youth Speaker), name: type, widget: string }
      - { label: City, name: city, widget: string }
      - { label: Photo, name: photo, widget: image, required: false, default: assets/default.jpg }
