backend:
  name: git-gateway
  repo: sharibarboza/FilcanJS #replace with your username/repo
  branch: dev

media_folder: static/assets
public_folder: /assets

collections:
  - name: campmeeting_date
    label: Campmeeting Date
    folder: cms/dates
    create: true
    fields:
      - { label: Unique title to file this date (e.g. Camp Meeting 2019), name: title, widget: string }
      - { label: Date, name: date, widget: datetime }

  - name: posters
    label: Campmeeting Poster
    folder: cms/posters
    create: true
    fields:
      - { label: Campmeeting Year, name: title, widget: number, valueType: int, min:2019 }
      - { label: Poster, name: poster, widget: image }

  - name: leadership
    label: Leadership
    folder: cms/leadership
    create: true
    fields:
      - { label: Unique title to file this executive (e.g. VP-Edmonton), name: title, widget: string }
      - { label: Executive Type, name: type, widget: select, options: ['Officer', 'Board VP', 'Adviser', 'Chair', 'Youth'] }
      - { label: Executive Position, name: position, widget: string }
      - { label: Name, name: name, widget: string }
      - { label: Email, name: email, widget: string, required: false, default: '' }
      - { label: Photo, name: photo, widget: image, default: /assets/default.jpg }

  - name: church
    label: Church
    folder: cms/churches
    create: true
    fields:
      - { label: Name of church, name: title }
      - { label: City/Town, name: city, widget: string }
      - { label: Current Pastor, name: pastor, widget: string, required: false, default: '' }
      - { label: Address, name: address, widget: string }
      - { label: Phone, name: phone, widget: string, required: false, default: '' }
      - { label: Website, name: website, widget: string, required: false, default: '' }
      - { label: Photo, name: photo, widget: image, required: false, default: /assets/adventist_logo.png }

  - name: pages
    label: Pages
    files:
      - label: History Page
        name: history
        file: cms/pages/history/history.md
        fields:
          - { label: Title of Page, name: title, widget: string }
          - { label: Photo, name: photo, widget: image }
          - { label: Text Content, name: content, widget: markdown }

  - name: bylaws
    label: Bylaws
    folder: cms/files/bylaws
    create: false
    fields:
      - { label: Title of Bylaw File, name: title, widget: string }
      - { label: File, name: file, widget: file }
      - { label: Text Content, name: content, widget: markdown }

  - name: reports
    label: Annual Reports
    folder: cms/files/reports
    create: true
    fields:
      - { label: Title of Report, name: title, widget: string }
      - { label: File, name: file, widget: file }

  - name: grid
    label: Grid Images
    folder: cms/grid
    create: true
    fields:
      - { label: Photo Number (e.g. Photo 1), name: title, widget: string }
      - { label: Event, name: event, widget: string }
      - { label: Caption, name: caption, widget: string }
      - { label: Photo, name: photo, widget: image }

  - name: theme
    label: Camp Meeting Theme
    folder: cms/theme
    fields:
      - { label: Theme Slogan, name: title, widget: string }
      - { label: Filipino Translation, name: filipino, widget: string }
      - { label: Bible Verse Text, name: versetext, widget: string }
      - { label: Bible Verse (e.g. Luke 14:23), name: verse, widget: string }

  - name: speakers
    label: Camp Meeting Speakers
    folder: cms/speakers
    create: true
    fields:
      - { label: Name of speaker, name: title, widget: string }
      - { label: Type of speaker (e.g. Youth Speaker), name: type, widget: string }
      - { label: Email, name: email, widget: string }
      - { label: Photo, name: photo, widget: image, required: false, default: /assets/default.jpg }

  - name: faq
    label: Camp Meeting FAQ
    folder: cms/faq
    create: true
    fields:
      - { label: Question, name: title, widget: string }
      - { label: Answer, name: answer, widget: text }

  - name: contact
    label: Contact Information
    folder: cms/contact
    create: true
    fields:
      - { label: Email, name: title, widget: string }
      - { label: Phone Number, name: phone, widget: string }

  - name: meetings
    label: Organizational Meetings
    folder: cms/meetings
    create: true
    fields:
      - { label: Date and time, name: title, widget: datetime }
      - { label: Location name (e.g. Foothills Camp), name: location, widget: string }
      - { label: Address, name: address, widget: string }
      - { label: Description (optional additional information), name: description, widget: string, required: false, default: '' }

  - name: resources
    label: Resource Files
    folder: cms/files/resources
    create: true
    fields:
      - { label: Title of File, name: title, widget: string }
      - { label: Category, name: type, widget: select, options: ['General', 'Sports Tournaments/Parlor Games', 'Social & Cultural Activities', 'Worship Services', 'Souvenir Programs'], default='General' }
      - { label: File, name: file, widget: file }

  - name: minutes
    label: Meeting Minutes
    folder: cms/files/minutes
    create: true
    fields:
      - { label: Title of Meeting Minutes (Must be unique), name: title, widget: string }
      - { label: Date of Meeting, name: date, widget: date }
      - { label: File, name: file, widget: file }

  - name: camp_info
    label: Camp Meeting Info
    folder: cms/info
    create: true
    fields:
      - { label: Info, name: info, widget: string }

  - name: schedules
    label: Schedule Images
    folder: cms/files/schedules
    create: true
    fields:
      - { label: Title of Schedule, name: title, widget: string, pattern: ['^.{1,40}$', "Title must not exceed 40 characters."], required: true }
      - { label: Number Position of Photo, name: position, widget: number, min: 1, step: 1, value_type: int }
      - { label: Photo, name: photo, widget: image }



