backend:
  name: github
  repo: sharibarboza/FilcanJS #replace with your username/repo

media_folder: static/assets
public_folder: /assets

collections:
  - name: campmeeting_date
    label: Campmeeting Date
    folder: dates
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Date, name: date, widget: date }

  - name: leadership
    label: Leadership
    folder: leadership
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Name, name: name, widget: string }
      - { label: Church, name: church, widget: string, required: false }
      - { label: Photo, name: photo, widget: image, required: false }
      - { label: Officer, name: officer, widget: boolean }
